version: "3.8"

networks:
  network_bank:
    driver: bridge

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: bank-nginx
    ports:
      - "8040:80"
    restart: unless-stopped
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/upstream.conf:/etc/nginx/conf.d/upstream.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    networks:
      - network_bank

  api:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: bank-api
    volumes:
      - ./:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    restart: unless-stopped
    tty: true
    networks:
      - network_bank
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: bank-mysql
    ports:
      - "3340:3306"
    volumes:
      - ./.data/mysql:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: bank
      MYSQL_USER: bank
      MYSQL_PASSWORD: bank
      MYSQL_ROOT_PASSWORD: root
    networks:
      - network_bank
