version: '3.7'
services:
  tntbnb-front:
    container_name: tntbnb-front
    build:
      context: .
      target: 'develop-stage'
    ports:
      - '83:83'
    volumes:
      - '.:/app'
    command: /bin/sh -c "npm install && quasar dev"
