import { boot } from 'quasar/wrappers';
import BankMain from 'src/layouts/BankMain.vue';
import BankMenu from 'src/components/BankMenu.vue';
import BankMenuHeader from 'src/components/BankMenuHeader.vue';
import BankBreadcrumbs from 'src/components/BankBreadcrumbs.vue';
import BiTable from 'src/components/BiTable.vue';
import BiSearch from 'src/components/BiSearch.vue';
import BankDropdownLanguage from 'src/components/BankDropdownLanguage.vue';
import BankSelectLanguage from 'src/components/BankSelectLanguage.vue';
import BiSelectSubdomain from 'src/components/BiSelectSubdomain.vue';
import BiReportsCard from 'src/components/BiReportsCard.vue';
import BiPagination from 'src/components/BiPagination.vue';
import BankProfile from 'src/components/BankProfile.vue';
import BankLogo from 'src/components/BankLogo.vue';
import BiTabs from 'src/components/BiTabs.vue';
import BiDate from 'src/components/BiDate.vue';
import BiDropdownExport from 'src/components/BiDropdownExport.vue';
import BiDropdownActions from 'src/components/BiDropdownActions.vue';
import BiModal from 'src/components/BiModal.vue';
import BiModalFooter from 'src/components/BiModalFooter.vue';
import BiFilterComponent from 'src/components/BiFilterComponent.vue';
import BiRisComponent from 'src/components/BiRisComponent.vue';
import BiNoData from 'src/components/BiNoData.vue';
import BiCardUser from 'src/components/BiCardUser.vue';
import BankCountryFlag from 'vue-country-flag-next';
import { VueDraggableNext } from 'vue-draggable-next';

export default boot(({ app }) => {
  app.component('VueDraggableNext', VueDraggableNext);
  app.component('BankMain', BankMain);
  app.component('BankMenu', BankMenu);
  app.component('BiDate', BiDate);
  app.component('BiCardUser', BiCardUser);
  app.component('BankMenuHeader', BankMenuHeader);
  app.component('BankBreadcrumbs', BankBreadcrumbs);
  app.component('BiTable', BiTable);
  app.component('BiSearch', BiSearch);
  app.component('BiNoData', BiNoData);
  app.component('BankDropdownLanguage', BankDropdownLanguage);
  app.component('BankSelectLanguage', BankSelectLanguage);
  app.component('BiSelectSubdomain', BiSelectSubdomain);
  app.component('BiRisComponent', BiRisComponent);
  app.component('BiFilterComponent', BiFilterComponent);
  app.component('BankCountryFlag', BankCountryFlag);
  app.component('BiReportsCard', BiReportsCard);
  app.component('BiPagination', BiPagination);
  app.component('BankProfile', BankProfile);
  app.component('BiModal', BiModal);
  app.component('BiTabs', BiTabs);
  app.component('BiModalFooter', BiModalFooter);
  app.component('BiDropdownActions', BiDropdownActions);
  app.component('BiDropdownExport', BiDropdownExport);
  app.component('BankLogo', BankLogo);
});
